spring:
  data:
    mongodb:
      database: testdb
      host: localhost
      port: 27017
server:
  error:
    include-stacktrace: never
    include-message: always
  compression:
    enabled: true
  http2:
    enabled: true
